server:
  port: 8080
  servlet:
    context-path: /
spring:
  jpa:
    generate-ddl: true
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:h2:./test
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false